
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 06 16:33:35 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 45;
  public static final int CONST = 8;
  public static final int NOTEQUAL = 29;
  public static final int LPAREN = 11;
  public static final int GREATER = 32;
  public static final int SEMI = 16;
  public static final int CONTINUE = 20;
  public static final int MINUS = 37;
  public static final int RPAREN = 12;
  public static final int AND = 34;
  public static final int OR = 35;
  public static final int BOOL = 26;
  public static final int COMMA = 15;
  public static final int CLASS = 3;
  public static final int INC = 41;
  public static final int DIV = 40;
  public static final int GEQ = 30;
  public static final int PLUS = 36;
  public static final int LESSER = 33;
  public static final int IF = 22;
  public static final int DOT = 17;
  public static final int EQUAL2 = 28;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int EQUAL = 27;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int MUL = 38;
  public static final int NUMBER = 43;
  public static final int MOD = 39;
  public static final int LSQBRACKET = 13;
  public static final int IDENT = 44;
  public static final int BREAK = 19;
  public static final int VOID = 5;
  public static final int LBRACE = 9;
  public static final int ELSE = 23;
  public static final int READ = 21;
  public static final int WHILE = 25;
  public static final int RBRACE = 10;
  public static final int EXTENDS = 4;
  public static final int PROG = 2;
  public static final int LEQ = 31;
  public static final int RSQBRACKET = 14;
  public static final int DEC = 42;
  public static final int PRINT = 18;
  public static final int DO = 24;
}

